// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-update-go-agent/pkg"
)

type GateRunner struct {
	RunTargetStub        func(context.Context, string, string) (string, int, error)
	runTargetMutex       sync.RWMutex
	runTargetArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	runTargetReturns struct {
		result1 string
		result2 int
		result3 error
	}
	runTargetReturnsOnCall map[int]struct {
		result1 string
		result2 int
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GateRunner) RunTarget(arg1 context.Context, arg2 string, arg3 string) (string, int, error) {
	fake.runTargetMutex.Lock()
	ret, specificReturn := fake.runTargetReturnsOnCall[len(fake.runTargetArgsForCall)]
	fake.runTargetArgsForCall = append(fake.runTargetArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.RunTargetStub
	fakeReturns := fake.runTargetReturns
	fake.recordInvocation("RunTarget", []interface{}{arg1, arg2, arg3})
	fake.runTargetMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *GateRunner) RunTargetCallCount() int {
	fake.runTargetMutex.RLock()
	defer fake.runTargetMutex.RUnlock()
	return len(fake.runTargetArgsForCall)
}

func (fake *GateRunner) RunTargetCalls(stub func(context.Context, string, string) (string, int, error)) {
	fake.runTargetMutex.Lock()
	defer fake.runTargetMutex.Unlock()
	fake.RunTargetStub = stub
}

func (fake *GateRunner) RunTargetArgsForCall(i int) (context.Context, string, string) {
	fake.runTargetMutex.RLock()
	defer fake.runTargetMutex.RUnlock()
	argsForCall := fake.runTargetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GateRunner) RunTargetReturns(result1 string, result2 int, result3 error) {
	fake.runTargetMutex.Lock()
	defer fake.runTargetMutex.Unlock()
	fake.RunTargetStub = nil
	fake.runTargetReturns = struct {
		result1 string
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *GateRunner) RunTargetReturnsOnCall(i int, result1 string, result2 int, result3 error) {
	fake.runTargetMutex.Lock()
	defer fake.runTargetMutex.Unlock()
	fake.RunTargetStub = nil
	if fake.runTargetReturnsOnCall == nil {
		fake.runTargetReturnsOnCall = make(map[int]struct {
			result1 string
			result2 int
			result3 error
		})
	}
	fake.runTargetReturnsOnCall[i] = struct {
		result1 string
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *GateRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GateRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GateRunner = new(GateRunner)
