// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-update-go-agent/pkg"
)

type GhCli struct {
	CreateDraftPRStub        func(context.Context, string, string, string, string, string) (string, error)
	createDraftPRMutex       sync.RWMutex
	createDraftPRArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 string
	}
	createDraftPRReturns struct {
		result1 string
		result2 error
	}
	createDraftPRReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	FindOpenPRByHeadStub        func(context.Context, string, string) (string, error)
	findOpenPRByHeadMutex       sync.RWMutex
	findOpenPRByHeadArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findOpenPRByHeadReturns struct {
		result1 string
		result2 error
	}
	findOpenPRByHeadReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ViewPRStub        func(context.Context, string) (string, bool, error)
	viewPRMutex       sync.RWMutex
	viewPRArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	viewPRReturns struct {
		result1 string
		result2 bool
		result3 error
	}
	viewPRReturnsOnCall map[int]struct {
		result1 string
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GhCli) CreateDraftPR(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string, arg6 string) (string, error) {
	fake.createDraftPRMutex.Lock()
	ret, specificReturn := fake.createDraftPRReturnsOnCall[len(fake.createDraftPRArgsForCall)]
	fake.createDraftPRArgsForCall = append(fake.createDraftPRArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 string
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.CreateDraftPRStub
	fakeReturns := fake.createDraftPRReturns
	fake.recordInvocation("CreateDraftPR", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.createDraftPRMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GhCli) CreateDraftPRCallCount() int {
	fake.createDraftPRMutex.RLock()
	defer fake.createDraftPRMutex.RUnlock()
	return len(fake.createDraftPRArgsForCall)
}

func (fake *GhCli) CreateDraftPRCalls(stub func(context.Context, string, string, string, string, string) (string, error)) {
	fake.createDraftPRMutex.Lock()
	defer fake.createDraftPRMutex.Unlock()
	fake.CreateDraftPRStub = stub
}

func (fake *GhCli) CreateDraftPRArgsForCall(i int) (context.Context, string, string, string, string, string) {
	fake.createDraftPRMutex.RLock()
	defer fake.createDraftPRMutex.RUnlock()
	argsForCall := fake.createDraftPRArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *GhCli) CreateDraftPRReturns(result1 string, result2 error) {
	fake.createDraftPRMutex.Lock()
	defer fake.createDraftPRMutex.Unlock()
	fake.CreateDraftPRStub = nil
	fake.createDraftPRReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GhCli) CreateDraftPRReturnsOnCall(i int, result1 string, result2 error) {
	fake.createDraftPRMutex.Lock()
	defer fake.createDraftPRMutex.Unlock()
	fake.CreateDraftPRStub = nil
	if fake.createDraftPRReturnsOnCall == nil {
		fake.createDraftPRReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createDraftPRReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GhCli) FindOpenPRByHead(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.findOpenPRByHeadMutex.Lock()
	ret, specificReturn := fake.findOpenPRByHeadReturnsOnCall[len(fake.findOpenPRByHeadArgsForCall)]
	fake.findOpenPRByHeadArgsForCall = append(fake.findOpenPRByHeadArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindOpenPRByHeadStub
	fakeReturns := fake.findOpenPRByHeadReturns
	fake.recordInvocation("FindOpenPRByHead", []interface{}{arg1, arg2, arg3})
	fake.findOpenPRByHeadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GhCli) FindOpenPRByHeadCallCount() int {
	fake.findOpenPRByHeadMutex.RLock()
	defer fake.findOpenPRByHeadMutex.RUnlock()
	return len(fake.findOpenPRByHeadArgsForCall)
}

func (fake *GhCli) FindOpenPRByHeadCalls(stub func(context.Context, string, string) (string, error)) {
	fake.findOpenPRByHeadMutex.Lock()
	defer fake.findOpenPRByHeadMutex.Unlock()
	fake.FindOpenPRByHeadStub = stub
}

func (fake *GhCli) FindOpenPRByHeadArgsForCall(i int) (context.Context, string, string) {
	fake.findOpenPRByHeadMutex.RLock()
	defer fake.findOpenPRByHeadMutex.RUnlock()
	argsForCall := fake.findOpenPRByHeadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GhCli) FindOpenPRByHeadReturns(result1 string, result2 error) {
	fake.findOpenPRByHeadMutex.Lock()
	defer fake.findOpenPRByHeadMutex.Unlock()
	fake.FindOpenPRByHeadStub = nil
	fake.findOpenPRByHeadReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GhCli) FindOpenPRByHeadReturnsOnCall(i int, result1 string, result2 error) {
	fake.findOpenPRByHeadMutex.Lock()
	defer fake.findOpenPRByHeadMutex.Unlock()
	fake.FindOpenPRByHeadStub = nil
	if fake.findOpenPRByHeadReturnsOnCall == nil {
		fake.findOpenPRByHeadReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.findOpenPRByHeadReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GhCli) ViewPR(arg1 context.Context, arg2 string) (string, bool, error) {
	fake.viewPRMutex.Lock()
	ret, specificReturn := fake.viewPRReturnsOnCall[len(fake.viewPRArgsForCall)]
	fake.viewPRArgsForCall = append(fake.viewPRArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ViewPRStub
	fakeReturns := fake.viewPRReturns
	fake.recordInvocation("ViewPR", []interface{}{arg1, arg2})
	fake.viewPRMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *GhCli) ViewPRCallCount() int {
	fake.viewPRMutex.RLock()
	defer fake.viewPRMutex.RUnlock()
	return len(fake.viewPRArgsForCall)
}

func (fake *GhCli) ViewPRCalls(stub func(context.Context, string) (string, bool, error)) {
	fake.viewPRMutex.Lock()
	defer fake.viewPRMutex.Unlock()
	fake.ViewPRStub = stub
}

func (fake *GhCli) ViewPRArgsForCall(i int) (context.Context, string) {
	fake.viewPRMutex.RLock()
	defer fake.viewPRMutex.RUnlock()
	argsForCall := fake.viewPRArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GhCli) ViewPRReturns(result1 string, result2 bool, result3 error) {
	fake.viewPRMutex.Lock()
	defer fake.viewPRMutex.Unlock()
	fake.ViewPRStub = nil
	fake.viewPRReturns = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *GhCli) ViewPRReturnsOnCall(i int, result1 string, result2 bool, result3 error) {
	fake.viewPRMutex.Lock()
	defer fake.viewPRMutex.Unlock()
	fake.ViewPRStub = nil
	if fake.viewPRReturnsOnCall == nil {
		fake.viewPRReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
			result3 error
		})
	}
	fake.viewPRReturnsOnCall[i] = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *GhCli) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GhCli) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GhCli = new(GhCli)
