// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-update-go-agent/pkg"
)

type GhCli struct {
	CreatePRStub        func(context.Context, string, string, string, string, string, pkg.PRTarget, string) (string, error)
	createPRMutex       sync.RWMutex
	createPRArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 string
		arg7 pkg.PRTarget
		arg8 string
	}
	createPRReturns struct {
		result1 string
		result2 error
	}
	createPRReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	FindOpenPRByHeadStub        func(context.Context, string, string) (string, error)
	findOpenPRByHeadMutex       sync.RWMutex
	findOpenPRByHeadArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findOpenPRByHeadReturns struct {
		result1 string
		result2 error
	}
	findOpenPRByHeadReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ViewPRStub        func(context.Context, string) (string, bool, error)
	viewPRMutex       sync.RWMutex
	viewPRArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	viewPRReturns struct {
		result1 string
		result2 bool
		result3 error
	}
	viewPRReturnsOnCall map[int]struct {
		result1 string
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GhCli) CreatePR(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string, arg6 string, arg7 pkg.PRTarget, arg8 string) (string, error) {
	fake.createPRMutex.Lock()
	ret, specificReturn := fake.createPRReturnsOnCall[len(fake.createPRArgsForCall)]
	fake.createPRArgsForCall = append(fake.createPRArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 string
		arg7 pkg.PRTarget
		arg8 string
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8})
	stub := fake.CreatePRStub
	fakeReturns := fake.createPRReturns
	fake.recordInvocation("CreatePR", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8})
	fake.createPRMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GhCli) CreatePRCallCount() int {
	fake.createPRMutex.RLock()
	defer fake.createPRMutex.RUnlock()
	return len(fake.createPRArgsForCall)
}

func (fake *GhCli) CreatePRCalls(stub func(context.Context, string, string, string, string, string, pkg.PRTarget, string) (string, error)) {
	fake.createPRMutex.Lock()
	defer fake.createPRMutex.Unlock()
	fake.CreatePRStub = stub
}

func (fake *GhCli) CreatePRArgsForCall(i int) (context.Context, string, string, string, string, string, pkg.PRTarget, string) {
	fake.createPRMutex.RLock()
	defer fake.createPRMutex.RUnlock()
	argsForCall := fake.createPRArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7, argsForCall.arg8
}

func (fake *GhCli) CreatePRReturns(result1 string, result2 error) {
	fake.createPRMutex.Lock()
	defer fake.createPRMutex.Unlock()
	fake.CreatePRStub = nil
	fake.createPRReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GhCli) CreatePRReturnsOnCall(i int, result1 string, result2 error) {
	fake.createPRMutex.Lock()
	defer fake.createPRMutex.Unlock()
	fake.CreatePRStub = nil
	if fake.createPRReturnsOnCall == nil {
		fake.createPRReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createPRReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GhCli) FindOpenPRByHead(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.findOpenPRByHeadMutex.Lock()
	ret, specificReturn := fake.findOpenPRByHeadReturnsOnCall[len(fake.findOpenPRByHeadArgsForCall)]
	fake.findOpenPRByHeadArgsForCall = append(fake.findOpenPRByHeadArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindOpenPRByHeadStub
	fakeReturns := fake.findOpenPRByHeadReturns
	fake.recordInvocation("FindOpenPRByHead", []interface{}{arg1, arg2, arg3})
	fake.findOpenPRByHeadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GhCli) FindOpenPRByHeadCallCount() int {
	fake.findOpenPRByHeadMutex.RLock()
	defer fake.findOpenPRByHeadMutex.RUnlock()
	return len(fake.findOpenPRByHeadArgsForCall)
}

func (fake *GhCli) FindOpenPRByHeadCalls(stub func(context.Context, string, string) (string, error)) {
	fake.findOpenPRByHeadMutex.Lock()
	defer fake.findOpenPRByHeadMutex.Unlock()
	fake.FindOpenPRByHeadStub = stub
}

func (fake *GhCli) FindOpenPRByHeadArgsForCall(i int) (context.Context, string, string) {
	fake.findOpenPRByHeadMutex.RLock()
	defer fake.findOpenPRByHeadMutex.RUnlock()
	argsForCall := fake.findOpenPRByHeadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GhCli) FindOpenPRByHeadReturns(result1 string, result2 error) {
	fake.findOpenPRByHeadMutex.Lock()
	defer fake.findOpenPRByHeadMutex.Unlock()
	fake.FindOpenPRByHeadStub = nil
	fake.findOpenPRByHeadReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GhCli) FindOpenPRByHeadReturnsOnCall(i int, result1 string, result2 error) {
	fake.findOpenPRByHeadMutex.Lock()
	defer fake.findOpenPRByHeadMutex.Unlock()
	fake.FindOpenPRByHeadStub = nil
	if fake.findOpenPRByHeadReturnsOnCall == nil {
		fake.findOpenPRByHeadReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.findOpenPRByHeadReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GhCli) ViewPR(arg1 context.Context, arg2 string) (string, bool, error) {
	fake.viewPRMutex.Lock()
	ret, specificReturn := fake.viewPRReturnsOnCall[len(fake.viewPRArgsForCall)]
	fake.viewPRArgsForCall = append(fake.viewPRArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ViewPRStub
	fakeReturns := fake.viewPRReturns
	fake.recordInvocation("ViewPR", []interface{}{arg1, arg2})
	fake.viewPRMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *GhCli) ViewPRCallCount() int {
	fake.viewPRMutex.RLock()
	defer fake.viewPRMutex.RUnlock()
	return len(fake.viewPRArgsForCall)
}

func (fake *GhCli) ViewPRCalls(stub func(context.Context, string) (string, bool, error)) {
	fake.viewPRMutex.Lock()
	defer fake.viewPRMutex.Unlock()
	fake.ViewPRStub = stub
}

func (fake *GhCli) ViewPRArgsForCall(i int) (context.Context, string) {
	fake.viewPRMutex.RLock()
	defer fake.viewPRMutex.RUnlock()
	argsForCall := fake.viewPRArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GhCli) ViewPRReturns(result1 string, result2 bool, result3 error) {
	fake.viewPRMutex.Lock()
	defer fake.viewPRMutex.Unlock()
	fake.ViewPRStub = nil
	fake.viewPRReturns = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *GhCli) ViewPRReturnsOnCall(i int, result1 string, result2 bool, result3 error) {
	fake.viewPRMutex.Lock()
	defer fake.viewPRMutex.Unlock()
	fake.ViewPRStub = nil
	if fake.viewPRReturnsOnCall == nil {
		fake.viewPRReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
			result3 error
		})
	}
	fake.viewPRReturnsOnCall[i] = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *GhCli) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GhCli) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GhCli = new(GhCli)
