// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-update-go-agent/pkg/git"
)

type GitOps struct {
	ChangedFilesStub        func(context.Context, string) ([]string, error)
	changedFilesMutex       sync.RWMutex
	changedFilesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	changedFilesReturns struct {
		result1 []string
		result2 error
	}
	changedFilesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	CloneAtRefStub        func(context.Context, string, string, string) error
	cloneAtRefMutex       sync.RWMutex
	cloneAtRefArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	cloneAtRefReturns struct {
		result1 error
	}
	cloneAtRefReturnsOnCall map[int]struct {
		result1 error
	}
	CommitStub        func(context.Context, string, string, ...string) (string, error)
	commitMutex       sync.RWMutex
	commitArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 []string
	}
	commitReturns struct {
		result1 string
		result2 error
	}
	commitReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	CommittedFilesStub        func(context.Context, string) ([]string, error)
	committedFilesMutex       sync.RWMutex
	committedFilesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	committedFilesReturns struct {
		result1 []string
		result2 error
	}
	committedFilesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	LsRemoteTagsStub        func(context.Context, string) ([]string, error)
	lsRemoteTagsMutex       sync.RWMutex
	lsRemoteTagsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	lsRemoteTagsReturns struct {
		result1 []string
		result2 error
	}
	lsRemoteTagsReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	PushStub        func(context.Context, string, string) error
	pushMutex       sync.RWMutex
	pushArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	pushReturns struct {
		result1 error
	}
	pushReturnsOnCall map[int]struct {
		result1 error
	}
	RevListStub        func(context.Context, string, string) ([]string, error)
	revListMutex       sync.RWMutex
	revListArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	revListReturns struct {
		result1 []string
		result2 error
	}
	revListReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	ShowFileStub        func(context.Context, string, string, string) ([]byte, error)
	showFileMutex       sync.RWMutex
	showFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	showFileReturns struct {
		result1 []byte
		result2 error
	}
	showFileReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	SwitchNewBranchStub        func(context.Context, string, string) error
	switchNewBranchMutex       sync.RWMutex
	switchNewBranchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	switchNewBranchReturns struct {
		result1 error
	}
	switchNewBranchReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitOps) ChangedFiles(arg1 context.Context, arg2 string) ([]string, error) {
	fake.changedFilesMutex.Lock()
	ret, specificReturn := fake.changedFilesReturnsOnCall[len(fake.changedFilesArgsForCall)]
	fake.changedFilesArgsForCall = append(fake.changedFilesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ChangedFilesStub
	fakeReturns := fake.changedFilesReturns
	fake.recordInvocation("ChangedFiles", []interface{}{arg1, arg2})
	fake.changedFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitOps) ChangedFilesCallCount() int {
	fake.changedFilesMutex.RLock()
	defer fake.changedFilesMutex.RUnlock()
	return len(fake.changedFilesArgsForCall)
}

func (fake *GitOps) ChangedFilesCalls(stub func(context.Context, string) ([]string, error)) {
	fake.changedFilesMutex.Lock()
	defer fake.changedFilesMutex.Unlock()
	fake.ChangedFilesStub = stub
}

func (fake *GitOps) ChangedFilesArgsForCall(i int) (context.Context, string) {
	fake.changedFilesMutex.RLock()
	defer fake.changedFilesMutex.RUnlock()
	argsForCall := fake.changedFilesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitOps) ChangedFilesReturns(result1 []string, result2 error) {
	fake.changedFilesMutex.Lock()
	defer fake.changedFilesMutex.Unlock()
	fake.ChangedFilesStub = nil
	fake.changedFilesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) ChangedFilesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.changedFilesMutex.Lock()
	defer fake.changedFilesMutex.Unlock()
	fake.ChangedFilesStub = nil
	if fake.changedFilesReturnsOnCall == nil {
		fake.changedFilesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.changedFilesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) CloneAtRef(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.cloneAtRefMutex.Lock()
	ret, specificReturn := fake.cloneAtRefReturnsOnCall[len(fake.cloneAtRefArgsForCall)]
	fake.cloneAtRefArgsForCall = append(fake.cloneAtRefArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.CloneAtRefStub
	fakeReturns := fake.cloneAtRefReturns
	fake.recordInvocation("CloneAtRef", []interface{}{arg1, arg2, arg3, arg4})
	fake.cloneAtRefMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitOps) CloneAtRefCallCount() int {
	fake.cloneAtRefMutex.RLock()
	defer fake.cloneAtRefMutex.RUnlock()
	return len(fake.cloneAtRefArgsForCall)
}

func (fake *GitOps) CloneAtRefCalls(stub func(context.Context, string, string, string) error) {
	fake.cloneAtRefMutex.Lock()
	defer fake.cloneAtRefMutex.Unlock()
	fake.CloneAtRefStub = stub
}

func (fake *GitOps) CloneAtRefArgsForCall(i int) (context.Context, string, string, string) {
	fake.cloneAtRefMutex.RLock()
	defer fake.cloneAtRefMutex.RUnlock()
	argsForCall := fake.cloneAtRefArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitOps) CloneAtRefReturns(result1 error) {
	fake.cloneAtRefMutex.Lock()
	defer fake.cloneAtRefMutex.Unlock()
	fake.CloneAtRefStub = nil
	fake.cloneAtRefReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) CloneAtRefReturnsOnCall(i int, result1 error) {
	fake.cloneAtRefMutex.Lock()
	defer fake.cloneAtRefMutex.Unlock()
	fake.CloneAtRefStub = nil
	if fake.cloneAtRefReturnsOnCall == nil {
		fake.cloneAtRefReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cloneAtRefReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) Commit(arg1 context.Context, arg2 string, arg3 string, arg4 ...string) (string, error) {
	fake.commitMutex.Lock()
	ret, specificReturn := fake.commitReturnsOnCall[len(fake.commitArgsForCall)]
	fake.commitArgsForCall = append(fake.commitArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 []string
	}{arg1, arg2, arg3, arg4})
	stub := fake.CommitStub
	fakeReturns := fake.commitReturns
	fake.recordInvocation("Commit", []interface{}{arg1, arg2, arg3, arg4})
	fake.commitMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitOps) CommitCallCount() int {
	fake.commitMutex.RLock()
	defer fake.commitMutex.RUnlock()
	return len(fake.commitArgsForCall)
}

func (fake *GitOps) CommitCalls(stub func(context.Context, string, string, ...string) (string, error)) {
	fake.commitMutex.Lock()
	defer fake.commitMutex.Unlock()
	fake.CommitStub = stub
}

func (fake *GitOps) CommitArgsForCall(i int) (context.Context, string, string, []string) {
	fake.commitMutex.RLock()
	defer fake.commitMutex.RUnlock()
	argsForCall := fake.commitArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitOps) CommitReturns(result1 string, result2 error) {
	fake.commitMutex.Lock()
	defer fake.commitMutex.Unlock()
	fake.CommitStub = nil
	fake.commitReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) CommitReturnsOnCall(i int, result1 string, result2 error) {
	fake.commitMutex.Lock()
	defer fake.commitMutex.Unlock()
	fake.CommitStub = nil
	if fake.commitReturnsOnCall == nil {
		fake.commitReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.commitReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) CommittedFiles(arg1 context.Context, arg2 string) ([]string, error) {
	fake.committedFilesMutex.Lock()
	ret, specificReturn := fake.committedFilesReturnsOnCall[len(fake.committedFilesArgsForCall)]
	fake.committedFilesArgsForCall = append(fake.committedFilesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CommittedFilesStub
	fakeReturns := fake.committedFilesReturns
	fake.recordInvocation("CommittedFiles", []interface{}{arg1, arg2})
	fake.committedFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitOps) CommittedFilesCallCount() int {
	fake.committedFilesMutex.RLock()
	defer fake.committedFilesMutex.RUnlock()
	return len(fake.committedFilesArgsForCall)
}

func (fake *GitOps) CommittedFilesCalls(stub func(context.Context, string) ([]string, error)) {
	fake.committedFilesMutex.Lock()
	defer fake.committedFilesMutex.Unlock()
	fake.CommittedFilesStub = stub
}

func (fake *GitOps) CommittedFilesArgsForCall(i int) (context.Context, string) {
	fake.committedFilesMutex.RLock()
	defer fake.committedFilesMutex.RUnlock()
	argsForCall := fake.committedFilesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitOps) CommittedFilesReturns(result1 []string, result2 error) {
	fake.committedFilesMutex.Lock()
	defer fake.committedFilesMutex.Unlock()
	fake.CommittedFilesStub = nil
	fake.committedFilesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) CommittedFilesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.committedFilesMutex.Lock()
	defer fake.committedFilesMutex.Unlock()
	fake.CommittedFilesStub = nil
	if fake.committedFilesReturnsOnCall == nil {
		fake.committedFilesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.committedFilesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) LsRemoteTags(arg1 context.Context, arg2 string) ([]string, error) {
	fake.lsRemoteTagsMutex.Lock()
	ret, specificReturn := fake.lsRemoteTagsReturnsOnCall[len(fake.lsRemoteTagsArgsForCall)]
	fake.lsRemoteTagsArgsForCall = append(fake.lsRemoteTagsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LsRemoteTagsStub
	fakeReturns := fake.lsRemoteTagsReturns
	fake.recordInvocation("LsRemoteTags", []interface{}{arg1, arg2})
	fake.lsRemoteTagsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitOps) LsRemoteTagsCallCount() int {
	fake.lsRemoteTagsMutex.RLock()
	defer fake.lsRemoteTagsMutex.RUnlock()
	return len(fake.lsRemoteTagsArgsForCall)
}

func (fake *GitOps) LsRemoteTagsCalls(stub func(context.Context, string) ([]string, error)) {
	fake.lsRemoteTagsMutex.Lock()
	defer fake.lsRemoteTagsMutex.Unlock()
	fake.LsRemoteTagsStub = stub
}

func (fake *GitOps) LsRemoteTagsArgsForCall(i int) (context.Context, string) {
	fake.lsRemoteTagsMutex.RLock()
	defer fake.lsRemoteTagsMutex.RUnlock()
	argsForCall := fake.lsRemoteTagsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitOps) LsRemoteTagsReturns(result1 []string, result2 error) {
	fake.lsRemoteTagsMutex.Lock()
	defer fake.lsRemoteTagsMutex.Unlock()
	fake.LsRemoteTagsStub = nil
	fake.lsRemoteTagsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) LsRemoteTagsReturnsOnCall(i int, result1 []string, result2 error) {
	fake.lsRemoteTagsMutex.Lock()
	defer fake.lsRemoteTagsMutex.Unlock()
	fake.LsRemoteTagsStub = nil
	if fake.lsRemoteTagsReturnsOnCall == nil {
		fake.lsRemoteTagsReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.lsRemoteTagsReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) Push(arg1 context.Context, arg2 string, arg3 string) error {
	fake.pushMutex.Lock()
	ret, specificReturn := fake.pushReturnsOnCall[len(fake.pushArgsForCall)]
	fake.pushArgsForCall = append(fake.pushArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.PushStub
	fakeReturns := fake.pushReturns
	fake.recordInvocation("Push", []interface{}{arg1, arg2, arg3})
	fake.pushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitOps) PushCallCount() int {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	return len(fake.pushArgsForCall)
}

func (fake *GitOps) PushCalls(stub func(context.Context, string, string) error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = stub
}

func (fake *GitOps) PushArgsForCall(i int) (context.Context, string, string) {
	fake.pushMutex.RLock()
	defer fake.pushMutex.RUnlock()
	argsForCall := fake.pushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GitOps) PushReturns(result1 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	fake.pushReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) PushReturnsOnCall(i int, result1 error) {
	fake.pushMutex.Lock()
	defer fake.pushMutex.Unlock()
	fake.PushStub = nil
	if fake.pushReturnsOnCall == nil {
		fake.pushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) RevList(arg1 context.Context, arg2 string, arg3 string) ([]string, error) {
	fake.revListMutex.Lock()
	ret, specificReturn := fake.revListReturnsOnCall[len(fake.revListArgsForCall)]
	fake.revListArgsForCall = append(fake.revListArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.RevListStub
	fakeReturns := fake.revListReturns
	fake.recordInvocation("RevList", []interface{}{arg1, arg2, arg3})
	fake.revListMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitOps) RevListCallCount() int {
	fake.revListMutex.RLock()
	defer fake.revListMutex.RUnlock()
	return len(fake.revListArgsForCall)
}

func (fake *GitOps) RevListCalls(stub func(context.Context, string, string) ([]string, error)) {
	fake.revListMutex.Lock()
	defer fake.revListMutex.Unlock()
	fake.RevListStub = stub
}

func (fake *GitOps) RevListArgsForCall(i int) (context.Context, string, string) {
	fake.revListMutex.RLock()
	defer fake.revListMutex.RUnlock()
	argsForCall := fake.revListArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GitOps) RevListReturns(result1 []string, result2 error) {
	fake.revListMutex.Lock()
	defer fake.revListMutex.Unlock()
	fake.RevListStub = nil
	fake.revListReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) RevListReturnsOnCall(i int, result1 []string, result2 error) {
	fake.revListMutex.Lock()
	defer fake.revListMutex.Unlock()
	fake.RevListStub = nil
	if fake.revListReturnsOnCall == nil {
		fake.revListReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.revListReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitOps) ShowFile(arg1 context.Context, arg2 string, arg3 string, arg4 string) ([]byte, error) {
	fake.showFileMutex.Lock()
	ret, specificReturn := fake.showFileReturnsOnCall[len(fake.showFileArgsForCall)]
	fake.showFileArgsForCall = append(fake.showFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.ShowFileStub
	fakeReturns := fake.showFileReturns
	fake.recordInvocation("ShowFile", []interface{}{arg1, arg2, arg3, arg4})
	fake.showFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitOps) ShowFileCallCount() int {
	fake.showFileMutex.RLock()
	defer fake.showFileMutex.RUnlock()
	return len(fake.showFileArgsForCall)
}

func (fake *GitOps) ShowFileCalls(stub func(context.Context, string, string, string) ([]byte, error)) {
	fake.showFileMutex.Lock()
	defer fake.showFileMutex.Unlock()
	fake.ShowFileStub = stub
}

func (fake *GitOps) ShowFileArgsForCall(i int) (context.Context, string, string, string) {
	fake.showFileMutex.RLock()
	defer fake.showFileMutex.RUnlock()
	argsForCall := fake.showFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitOps) ShowFileReturns(result1 []byte, result2 error) {
	fake.showFileMutex.Lock()
	defer fake.showFileMutex.Unlock()
	fake.ShowFileStub = nil
	fake.showFileReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitOps) ShowFileReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.showFileMutex.Lock()
	defer fake.showFileMutex.Unlock()
	fake.ShowFileStub = nil
	if fake.showFileReturnsOnCall == nil {
		fake.showFileReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.showFileReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitOps) SwitchNewBranch(arg1 context.Context, arg2 string, arg3 string) error {
	fake.switchNewBranchMutex.Lock()
	ret, specificReturn := fake.switchNewBranchReturnsOnCall[len(fake.switchNewBranchArgsForCall)]
	fake.switchNewBranchArgsForCall = append(fake.switchNewBranchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SwitchNewBranchStub
	fakeReturns := fake.switchNewBranchReturns
	fake.recordInvocation("SwitchNewBranch", []interface{}{arg1, arg2, arg3})
	fake.switchNewBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitOps) SwitchNewBranchCallCount() int {
	fake.switchNewBranchMutex.RLock()
	defer fake.switchNewBranchMutex.RUnlock()
	return len(fake.switchNewBranchArgsForCall)
}

func (fake *GitOps) SwitchNewBranchCalls(stub func(context.Context, string, string) error) {
	fake.switchNewBranchMutex.Lock()
	defer fake.switchNewBranchMutex.Unlock()
	fake.SwitchNewBranchStub = stub
}

func (fake *GitOps) SwitchNewBranchArgsForCall(i int) (context.Context, string, string) {
	fake.switchNewBranchMutex.RLock()
	defer fake.switchNewBranchMutex.RUnlock()
	argsForCall := fake.switchNewBranchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GitOps) SwitchNewBranchReturns(result1 error) {
	fake.switchNewBranchMutex.Lock()
	defer fake.switchNewBranchMutex.Unlock()
	fake.SwitchNewBranchStub = nil
	fake.switchNewBranchReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) SwitchNewBranchReturnsOnCall(i int, result1 error) {
	fake.switchNewBranchMutex.Lock()
	defer fake.switchNewBranchMutex.Unlock()
	fake.SwitchNewBranchStub = nil
	if fake.switchNewBranchReturnsOnCall == nil {
		fake.switchNewBranchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.switchNewBranchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitOps) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitOps) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.GitOps = new(GitOps)
