// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-update-go-agent/pkg"
)

type InstallationScope struct {
	AllowsStub        func(context.Context, string) pkg.ScopeVerdict
	allowsMutex       sync.RWMutex
	allowsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	allowsReturns struct {
		result1 pkg.ScopeVerdict
	}
	allowsReturnsOnCall map[int]struct {
		result1 pkg.ScopeVerdict
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *InstallationScope) Allows(arg1 context.Context, arg2 string) pkg.ScopeVerdict {
	fake.allowsMutex.Lock()
	ret, specificReturn := fake.allowsReturnsOnCall[len(fake.allowsArgsForCall)]
	fake.allowsArgsForCall = append(fake.allowsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.AllowsStub
	fakeReturns := fake.allowsReturns
	fake.recordInvocation("Allows", []interface{}{arg1, arg2})
	fake.allowsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *InstallationScope) AllowsCallCount() int {
	fake.allowsMutex.RLock()
	defer fake.allowsMutex.RUnlock()
	return len(fake.allowsArgsForCall)
}

func (fake *InstallationScope) AllowsCalls(stub func(context.Context, string) pkg.ScopeVerdict) {
	fake.allowsMutex.Lock()
	defer fake.allowsMutex.Unlock()
	fake.AllowsStub = stub
}

func (fake *InstallationScope) AllowsArgsForCall(i int) (context.Context, string) {
	fake.allowsMutex.RLock()
	defer fake.allowsMutex.RUnlock()
	argsForCall := fake.allowsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *InstallationScope) AllowsReturns(result1 pkg.ScopeVerdict) {
	fake.allowsMutex.Lock()
	defer fake.allowsMutex.Unlock()
	fake.AllowsStub = nil
	fake.allowsReturns = struct {
		result1 pkg.ScopeVerdict
	}{result1}
}

func (fake *InstallationScope) AllowsReturnsOnCall(i int, result1 pkg.ScopeVerdict) {
	fake.allowsMutex.Lock()
	defer fake.allowsMutex.Unlock()
	fake.AllowsStub = nil
	if fake.allowsReturnsOnCall == nil {
		fake.allowsReturnsOnCall = make(map[int]struct {
			result1 pkg.ScopeVerdict
		})
	}
	fake.allowsReturnsOnCall[i] = struct {
		result1 pkg.ScopeVerdict
	}{result1}
}

func (fake *InstallationScope) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *InstallationScope) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.InstallationScope = new(InstallationScope)
