// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-update-go-agent/pkg"
)

type ModuleResolver struct {
	ModulesStub        func(context.Context, string) ([]pkg.ModuleVersion, error)
	modulesMutex       sync.RWMutex
	modulesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	modulesReturns struct {
		result1 []pkg.ModuleVersion
		result2 error
	}
	modulesReturnsOnCall map[int]struct {
		result1 []pkg.ModuleVersion
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ModuleResolver) Modules(arg1 context.Context, arg2 string) ([]pkg.ModuleVersion, error) {
	fake.modulesMutex.Lock()
	ret, specificReturn := fake.modulesReturnsOnCall[len(fake.modulesArgsForCall)]
	fake.modulesArgsForCall = append(fake.modulesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ModulesStub
	fakeReturns := fake.modulesReturns
	fake.recordInvocation("Modules", []interface{}{arg1, arg2})
	fake.modulesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ModuleResolver) ModulesCallCount() int {
	fake.modulesMutex.RLock()
	defer fake.modulesMutex.RUnlock()
	return len(fake.modulesArgsForCall)
}

func (fake *ModuleResolver) ModulesCalls(stub func(context.Context, string) ([]pkg.ModuleVersion, error)) {
	fake.modulesMutex.Lock()
	defer fake.modulesMutex.Unlock()
	fake.ModulesStub = stub
}

func (fake *ModuleResolver) ModulesArgsForCall(i int) (context.Context, string) {
	fake.modulesMutex.RLock()
	defer fake.modulesMutex.RUnlock()
	argsForCall := fake.modulesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ModuleResolver) ModulesReturns(result1 []pkg.ModuleVersion, result2 error) {
	fake.modulesMutex.Lock()
	defer fake.modulesMutex.Unlock()
	fake.ModulesStub = nil
	fake.modulesReturns = struct {
		result1 []pkg.ModuleVersion
		result2 error
	}{result1, result2}
}

func (fake *ModuleResolver) ModulesReturnsOnCall(i int, result1 []pkg.ModuleVersion, result2 error) {
	fake.modulesMutex.Lock()
	defer fake.modulesMutex.Unlock()
	fake.ModulesStub = nil
	if fake.modulesReturnsOnCall == nil {
		fake.modulesReturnsOnCall = make(map[int]struct {
			result1 []pkg.ModuleVersion
			result2 error
		})
	}
	fake.modulesReturnsOnCall[i] = struct {
		result1 []pkg.ModuleVersion
		result2 error
	}{result1, result2}
}

func (fake *ModuleResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ModuleResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.ModuleResolver = new(ModuleResolver)
